title: Site de EmJako
logo: "/logo.png" # your photo (or logo) here
description:
  Ce site rassemble toutes les ressources liées aux publicatoins de Emmanuel Jakobowicz notamment ses ouvrages 
  <br><br>
  Emmanuel est data scientist, CEO de @stat4decision et auteur d'ouvrages notamment sur python.
  <br><br>
  <a href="https://www.stat4decision.com">Stat4decision</a> 
  
theme: jekyll-theme-minimal
